### ISSUE TITLE
Updating EVD definitions... error: Failed to sync database

### ISSUE THREAD

**Issue by gchorny** [victims/victims-client-java#30]
Just finished installing victims-client-java. Initial tests during the mvn install failed

 T E S T S
Running com.redhat.victims.cli.commands.ScanCommandTest
skipping /home/gchorny/software/victims/victims-client-java-master/.testdata/empty.jar (empty file)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec
Running com.redhat.victims.cli.RuntimeErrorTest
ERROR: Unexpected runtime error occurred!
java.lang.NullPointerException: Opps.. you broke it?
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec
Running com.redhat.victims.cli.ReplTest

Any attempts to synchronize the fail as well:
victims --verbose --update
Updating EVD definitions...
error: Failed to sync database
WARNING: Victims database is empty! Run command again with the --update flag.

Does this have anything to do with the fact that https://victi.ms is currently returning Error 503?

**Comment by gchorny** [comment]
Hmm now that victi.ms is back my updates are working fine. Mark this as resolved please.

**Comment by abn** [comment]
@gchorny thank you for letting us know. Marking as resolved.

**Comment by gchorny** [comment]
Error 503 is back :(

And as a result
$ victims --update
Updating EVD definitions...
error: Failed to sync database

**Comment by abn** [comment]
@gchorny we are looking into a longer term solution for the hosting issue. For now, I've bounced the service.
