### ISSUE TITLE
pom.xml - doesn't resolve dependencies from parent pom

### ISSUE THREAD

**Issue by kamal079** [victims/victims-client-java#32]
When tested against a maven project which inherits <dependencyManagement> from a parent pom, the dependencies list do not contain the dependencies from parent pom.

 Adding  the below lines to _PomScannerCommand.java_ helped me list all CVEs affecting my project. I'm not sure if you've kept this out intentionally. If not, I'd be glad to do a PR.
```
            Model model = pomReader.read(new FileReader(pomFile));
            List<Dependency> dependencyList = model.getDependencyManagement().getDependencies();
            dependencyList.addAll(model.getDependencies());
```

**Comment by ashcrow** [comment]
@gcmurphy Was it left out intentionally?

**Comment by gcmurphy** [comment]
Nope. It looks like a bug. Submitted PR https://github.com/victims/victims-client-java/pull/33. @kamal079 does that address the issue for you?

**Comment by kamal079** [comment]
Yes, it does. Thanks.
