### ISSUE TITLE
Make the API more well definied with Interfaces

### ISSUE THREAD

**Issue by jasinner** [victims/victims-client-java#34]
While it probably works when you know what to call when, the thing that it's not marked as API, rather blended into different classes and packages mixed with implementation, may lead someone to think that the API is subject to change without prior notice.

It would be ideal if there were some interfaces which would contain only the methods supposed to be called by the integrating application.

**Comment by gcmurphy** [comment]
Did you mean to create this against https://github.com/victims/victims-lib-java? This project was always intended to be a command line wrapper for victims-lib. It isn't intended to be used as an API.

**Comment by jasinner** [comment]
Whoops, yes, I meant to create it in victims-lib-java. Done now:
https://github.com/victims/victims-lib-java/issues/48
