### ISSUE TITLE
Victi.ms is down

### ISSUE THREAD

**Issue by OndraZizka** [victims/victims-client-java#41]
After few working updates, they stopped working.
Also https://victi.ms/ seems to be down (I guess it's the same thing).
Not sure where to put the issue, so I am putting it here.

**Comment by ashcrow** [comment]
Thanks @OndraZizka  Right now it looks like https://www.victi.ms/ is working but https://victi.ms is not. I'll take a look.

**Comment by ashcrow** [comment]
It looks like the DNS provider erroneously pointed the A record to a parking location causing the non www version to resolve but not actually make it anywhere. I've manually reverted it back to the proper IP address.

This should fix the issue. Sorry about that and thanks for reporting it!
